name: update

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/59 * * * *"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - run: node .github/actions/refreshStar.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        run: |
          git config --local user.email "daiwei521@126.com"
          git config --local user.name "edison1105"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "chore: refresh stars"
          git push